### ISSUE TITLE
Restore to Local mongodb instance?

### ISSUE THREAD

**Issue by ghost** [alexkravets/heroku-mongo-backup#8]
This is not really an issue, but more of a question on how I can restore the backup on my local machine to a local mongo db instance.

**Comment by alexkravets** [comment]
It requires adding some code to the gem. Right now it pulls defined file from the bucket.

If you don't feel like coding, then you can handle it by creating bucket pushing local db file to backups folder, set local vars and run restore command.

## Let me know if I can help you.

Alex

**Comment by alexkravets** [comment]
this feature is added in 0.4.2, please take a look at README for references

**Comment by ghost** [comment]
Thank you. This worked perfectly!
