### ISSUE TITLE
MONGOHQ || MONGOLAB on 'staging' environment?

### ISSUE THREAD

**Issue by taromurao** [alexkravets/heroku-mongo-backup#9]
I struggled a while when I tried to test heroku-mongo-back on my ''staging' app. I have RACK_ENV=staging, RAILS_ENV=staging.

How do you think of modifying below code

if((ENV['RAILS_ENV'] || ENV['RACK_ENV']) == 'production')

to

if(['production', 'staging'].include?(ENV['RAILS_ENV'] || ENV['RACK_ENV']))

Another solution is to simply inform users on the documentation, e.g. RAILS_ENV and/or RACK_ENV should be 'production'.

**Comment by alexkravets** [comment]
yes, this makes sense I'll add this with the next push

**Comment by alexkravets** [comment]
added in 0.4.2

**Comment by henrydjacob** [comment]
Can you make it generic. this doesn't work if environments named other than staging and production? I  my case i have environments for 'pilot' and 'test'

**Comment by jturolla** [comment]
I agree with henrydjacob, my staging was named test.

**Comment by alexkravets** [comment]
Guys, thanks for the feedback. I'll probably will not have time to fix it in near future. So if this is an issue for you, please go ahead and fix it (the code is pretty simple there) and I will merge pull request.
